### ISSUE TITLE
Uncaught TypeError: this.linterRegistry.unregister is not a function

### ISSUE THREAD

**Issue by bluepi0j** [Alchiadus/linter-verification#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-verification](https://github.com/alchiadus/linter-verification) package 0.5.1

### Stack Trace

Uncaught TypeError: this.linterRegistry.unregister is not a function

```
At /Users/bmac/.atom/packages/linter-verification/lib/linters/verification-linter.js:42

TypeError: this.linterRegistry.unregister is not a function
    at DafnyLinter.dispose (/packages/linter-verification/lib/linters/verification-linter.js:42:25)
    at /packages/linter-verification/lib/main.js:80:24
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:661:26)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:707:66)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1716:48)
    at HTMLElement.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -2:37.5.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:11.6.0 editor:newline (input.hidden-input)
     -2:10.5.0 autocomplete-plus:confirm (input.hidden-input)
     -2:08.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  8x -1:59.4.0 core:backspace (input.hidden-input)
  2x -1:55 autocomplete-plus:confirm (input.hidden-input)
     -1:48.2.0 editor:delete-to-beginning-of-line (input.hidden-input)
  5x -1:27.3.0 core:backspace (input.hidden-input)
     -1:22.5.0 editor:newline (input.hidden-input)
     -1:21 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:22.4.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.2 
busy-signal 1.4.3 
intentions 1.1.5 
language-dafny 0.1.0 
linter 2.2.0 
linter-ui-default 1.6.9 
linter-verification 0.5.1 
```

**Comment by Alchiadus** [comment]
Thank you for reporting this. This package was written with `linter` v1 in mind. Since then `linter` has released v2 of their API, so it's likely some issues may arrise.

I'm no longer actively developing `linter-verification`. I'm in the process of writing a new package specifically for Dafny: [`dafny-workbench`](https://github.com/Alchiadus/dafny-workbench). It has not yet been published to Atom's package registery, but can be installed via the command line as a git package with `apm install Alchiadus/dafny-workbench`. Atom will offer to update the package every time a new commit is pushed to the master branch of the repository.

It has been completely rewritten and should provide a (much) more stable experience, along with some other enhancements like the ability to stop a verification task (for example because there's infinite recursion in the verification process).

There is one bug that you may encounter that I am aware of. When you start Atom with several Dafny files already open, there may be a status bar icon for every Dafny file. Simply switching to any open file should properly hide them. As far as I've seen, this only occurs on Mac OS X.

If you're inclined to test `dafny-workbench`, any and all feedback or issue reports would be welcome!
